FROM maven:3.9.9-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -B dependency:go-offline
COPY . .
RUN mvn package -DskipTests

FROM openjdk:17-slim
COPY --from=build /app/target/explore-0.0.1-SNAPSHOT.jar app.jar
CMD [ "java", "-jar", "app.jar" ]