name: CI/CD Pipeline

on:
   push:
      branches:
      - master
   pull_request:
      branches:
      - master
      
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
      -  name: Checkout code
         uses: actions/checkout@v2
         
      -  name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            java-version: '17'
            distribution: temurin
      
      -  name: Build and Test with Maven
         run: mvn clean install -DskipTests
         
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      -  name: run scripts and push to registry
         run: |
           docker build -f Dockerfile.dev -t dhivakar15/docker-explore .
           docker push dhivakar15/docker-explore
           
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
          
      -  name: Deploy to EB
         uses: einaregilsson/beanstalk-deploy@v18
         with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: myfirstapp
            environment_name: Myfirstapp-env
            existing_bucket_name: elasticbeanstalk-us-east-1-277707100561
            region: us-east-1
            version_label: ${{ github.sha }} 
            deployment_package: deploy.zip